### ISSUE TITLE
Need to configure Mic and some mic not working.

### ISSUE THREAD

**Issue by gxstv** [YuantongL/YToke#2]
For those not working mic, I found https://rogueamoeba.com/loopback/ can be use as a alternative way and there is almost no latency for voice input. Maybe consider integrate with it?

**Comment by YuantongL** [comment]
Move the issue to the board. I don't think we can integrate Rogue Amoeba since it's not a framework we can pull to the project. But it is worth it to investigate their latency performance with microphone input then make potential improvement.

Also rogueamoeba and GarageBand seems able to select and mix audio source in their app, this is something we need as well.

**Comment by YuantongL** [comment]
With the permission fix (bfc302072f637e2fba0b9086d667bbfacb635339) and the microphone selector fix (https://github.com/YuantongL/YToke/commit/13c3f68a1c96eb914c7029e307de9f90c499e7f8), it should be good enough to cover this issue.

It will be the best if we can create aggregate device from the app, I tried to work with CoreAudio + AVAudioEngine to make it happen, I found it extremely hard to make it work without crash (being able to select multiple device, support plug/unplug)...

I think the fix is good enough for now, I will create another ticket to track future work.
